name: Android Pipeline

on:
  pull_request:
    branches:
      - 'main'

jobs:
  quality_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Ruby 2.6.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3    

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Set API key environment variable
        run: export API_BASE_URL=${{ secrets.API_BASE_URL }}

      - name: Set API key environment variable
        run: export API_KEY=${{ secrets.API_KEY }}

      - name: Run Unit Tests
        run: ./gradlew koverMergedReport

      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/kover/merged/xml/report.xml
          verbose: true

      - name: Run Detekt
        run: ./tools/linters/detekt/detekt.sh

      - name: Run Danger
        if: always()
        run: |
          bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_TOKEN }}
